version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: libreria-db
    restart: always
    ports:
      - "${DB_DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    env_file:
      - ./backend/.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - libreria-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: libreria-backend
    restart: always
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=db # Nombre del servicio de la base de datos
      - DB_PORT=${DB_DB_PORT} # Asegúrate de usar 5432 aquí
    env_file:
      - ./backend/.env
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3001:3001
    networks:
      - libreria-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: libreria-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 8383:8383
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - libreria-network

volumes:
  postgres_data:

networks:
  libreria-network:
