version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postsgress_container
    restart: always
    ports:
      - "${DB_DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
